#! /usr/bin/env python

import sys, os, glob
import numpy as np
from pyscf import gto
from TDDMRG_CM.utils.util_qm import make_full_dm
from TDDMRG_CM.utils.util_print import print_td_pcharge
from TDDMRG_CM.observables import extract_time, pcharge, pcharge_inputs


#============================#
#==== EXAMPLE INPUT FILE ====#
#============================#
'''
#== General ==#
dump_inputs = True
prefix = 'Acetylene-chloro'

#== System ==#
atoms = \
    \'''        # remove the leading '\'
     H    0.000    0.000    -2.926;
     C    0.000    0.000    -1.862;
     C    0.000    0.000    -0.653;
    Cl    0.000    0.000     1.060; 
    \'''        # remove the leading '\'
basis = '6-31g'
group = 'c2v'
orb_path = '/data/iwahyutama/Computations/TDDMRG_CM/Orbitals_DFT/Acetylene-chloro' + \
           '/B3LYP_6-31g_C2v/Acetylene-chloro.orb.npy'

#== CAS ==#
nCore = 0
nCAS = 33
nelec_t0 = 29
'''
#============================#





#==== Input file ====#
inp_file = str(sys.argv[1])
inputs = pcharge_inputs.get_inputs(inp_file)
if inputs['dump_inputs']:
    print('\nInput parameters:')
    for kw in inputs:
        print('  ', kw, ' = ', inputs[kw])
    print(' ')


#==== Sample directory from which the PDMs are loaded ====#
if inputs['sample_dir'] == 'DEFINE_LATER':
    inputs['sample_dir'] = './' + inputs['prefix'] + '.sample'    

    
#==== Setting up the system ====#
mol = gto.M(atom=inputs['atoms'], basis=inputs['basis'], ecp=inputs['ecp'],
            symmetry=inputs['group'])
atom_symbol = [mol.atom_symbol(i) for i in range(0, mol.natm)]
ovl = mol.intor('int1e_ovlp')
nocc = inputs['nCore'] + inputs['nCAS']
print('No. of bases = ', mol.nao)
print('No. of core orbitals = ', inputs['nCore'])
print('No. of CAS orbitals = ', inputs['nCAS'])


#==== Load and construct the orbitals ====#
orbs = np.zeros((2, mol.nao, nocc))
orbs[0,:,:] = orbs[1,:,:] = np.load(inputs['orb_path'])[:,0:nocc]


#==== Construct the time array ====#
tt = extract_time.get(inputs['sample_dir'])
idsort = np.argsort(tt)
n_tevo = len(tt)
print('Time evolution directory = ', inputs['sample_dir'])
print('Number of time points = ', n_tevo)


#==== Print partial charge values ====#
print('\nCalculating and printing partial charges:')
pdm_dir = glob.glob(inputs['sample_dir'] + '/tevo-*')
q_print = print_td_pcharge(atom_symbol, inputs['prefix'], n_tevo, 8, inputs['save_txt'],
                           inputs['save_npy'])
q_print.header()
for i in idsort:
    #== Construct the PDM ==#
    pdm = np.load(pdm_dir[i] + '/1pdm.npy')
    pdm_full = make_full_dm(inputs['nCore'], pdm)
    tr = np.sum( np.trace(pdm_full, axis1=1, axis2=2) )
    pdm_full = pdm_full * inputs['nelec_t0'] / np.abs(tr)
    print('Sample no. %d,  time = %.6f a.u.' % (i, tt[i]))
    print('  Path = ', pdm_dir[i])
    qmul, qlow = pcharge.calc(mol, pdm_full, orbs, ovl)
    q_print.print_pcharge(tt[i], qlow)

    
#==== Print footer (end) ====#
q_print.footer()
